(* Auto-generated from: /Users/fduarte/Library/CloudStorage/Dropbox-Personal/MyPackages/LongRunRisk-feat-gen-tests/Tests/FindRootOptim/fastRootOptions.wlt
   by WLTTestRefactor` on 2026-01-03
   DO NOT EDIT BY HAND. Edit the generator or the original sources instead.
*)

BeginPackage["WLTGenerated`fastRootOptions`"];

GenerateWLT::usage = "GenerateWLT[] writes the .wlt file. GenerateWLT[target] writes to target.";

Begin["`Private`"];

$sourceExpressions = {
    HoldComplete[BeginTestSection["fastRootOptions Tests"]],
    HoldComplete[Begin["FernandoDuarte`LongRunRisk`Tests`FindRootOptim`fastRootOptions`"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, {1., 2.}, Jacobian -> df1, Method -> "Secant"]; NumericQ[result] && Abs[result^2 - 2] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "method-secant-with-jacobian@@Tests/FindRootOptim/fastRootOptions.wlt:44,1-52,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f2, {1.5, 3.}, Jacobian -> df2, Method -> "Secant"]; NumericQ[result] && Abs[result^2 - 4] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "method-secant-nonbracketed@@Tests/FindRootOptim/fastRootOptions.wlt:94,1-103,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[fcos, {1., 2.}, Jacobian -> dfcos, Method -> "Brent"]; NumericQ[result] && Abs[Cos[result]] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "method-brent-bracketed@@Tests/FindRootOptim/fastRootOptions.wlt:145,1-154,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, {1., 2.}, Jacobian -> df1, "Return" -> "Rule"]; MatchQ[result, {_ -> _?NumericQ}]], True, TimeConstraint -> timeLimit, TestID -> "return-rule-option@@Tests/FindRootOptim/fastRootOptions.wlt:196,1-204,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, {1., 2.}, Jacobian -> df1]; NumericQ[result] && Abs[result^2 - 2] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "return-value-default@@Tests/FindRootOptim/fastRootOptions.wlt:246,1-255,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{resultRule, resultValue}, resultRule = fastRoot[fcos, {1., 2.}, Jacobian -> dfcos, "Return" -> "Rule"]; resultValue = fastRoot[fcos, {1., 2.}, Jacobian -> dfcos, "Return" -> "Value"]; Abs[resultRule[[1,2]] - resultValue] < 10^(-8)], True, TimeConstraint -> timeLimit, TestID -> "return-rule-vs-value-consistency@@Tests/FindRootOptim/fastRootOptions.wlt:297,1-307,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, {1., 2.}]; NumericQ[result] && Abs[result^2 - 2] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "no-jacobian-bracketed-brent@@Tests/FindRootOptim/fastRootOptions.wlt:349,1-358,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[fsin, {0., 1.}]; NumericQ[result] && Abs[Sin[result] - 0.5] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "no-jacobian-bracketed-trig@@Tests/FindRootOptim/fastRootOptions.wlt:400,1-409,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f2, {1.5, 3.}]; NumericQ[result] && Abs[result^2 - 4] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "no-jacobian-nonbracketed-secant@@Tests/FindRootOptim/fastRootOptions.wlt:451,1-460,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[fexp, {0.5, 1.5}]; NumericQ[result] && Abs[Exp[result] - 3] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "no-jacobian-nonbracketed-exp@@Tests/FindRootOptim/fastRootOptions.wlt:502,1-511,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, {1., 2.}, AccuracyGoal -> 10, PrecisionGoal -> 10]; NumericQ[result] && Abs[result^2 - 2] < 10^(-9)], True, TimeConstraint -> timeLimit, TestID -> "high-accuracy-goals@@Tests/FindRootOptim/fastRootOptions.wlt:553,1-561,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{badF, result}, badF[z_] := If[z[[1]] < 1.5, z[[1]]^2 - 2, Indeterminate]; result = Quiet[fastRoot[badF, {1., 2.}, Jacobian -> df1]]; result === $Failed], True, {}, TimeConstraint -> timeLimit, TestID -> "failure-nonnumeric-function-value@@Tests/FindRootOptim/fastRootOptions.wlt:603,1-613,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[fcubic, {1., 3.}]; NumericQ[result] && Abs[result^3 - 8] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "no-jacobian-cubic-root@@Tests/FindRootOptim/fastRootOptions.wlt:655,1-663,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, {2., 1.}, Jacobian -> df1]; result === $Failed], True, {FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot::badbounds}, TimeConstraint -> timeLimit, TestID -> "reversed-interval-badbounds@@Tests/FindRootOptim/fastRootOptions.wlt:705,1-714,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, {1., 2.}, Jacobian -> df1, Method -> "Secant", "Return" -> "Value"]; NumericQ[result] && Abs[result^2 - 2] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "combined-method-return-options@@Tests/FindRootOptim/fastRootOptions.wlt:756,1-765,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, {1., 2.}, Jacobian -> df1, AccuracyGoal -> 12, PrecisionGoal -> 12]; NumericQ[result] && Abs[result^2 - 2] < 10^(-11)], True, TimeConstraint -> timeLimit, TestID -> "high-accuracy-precision-goals@@Tests/FindRootOptim/fastRootOptions.wlt:807,1-816,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, {1., 2.}, Jacobian -> df1, MaxIterations -> 50]; NumericQ[result] && Abs[result^2 - 2] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "maxiterations-option@@Tests/FindRootOptim/fastRootOptions.wlt:858,1-866,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result, badDF}, badDF[z_] := 0; result = fastRoot[f1, {1., 2.}, Jacobian -> badDF]; NumericQ[result] && Abs[result^2 - 2] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "newton-fails-fallback@@Tests/FindRootOptim/fastRootOptions.wlt:908,1-917,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, {1.41, 1.42}, Jacobian -> df1]; NumericQ[result] && Abs[result^2 - 2] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "narrow-interval-convergence@@Tests/FindRootOptim/fastRootOptions.wlt:959,1-967,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, {1., 2.}, Jacobian -> df1, WorkingPrecision -> MachinePrecision]; NumericQ[result] && Abs[result^2 - 2] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "workingprecision-option@@Tests/FindRootOptim/fastRootOptions.wlt:1009,1-1018,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f2, {1.5, 3.}, Jacobian -> df2, Method -> Automatic]; NumericQ[result] && Abs[result^2 - 4] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "method-automatic-nonbracketed@@Tests/FindRootOptim/fastRootOptions.wlt:1060,1-1068,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = Quiet[fastRoot[f1, {1., 2.}, Jacobian -> df1]]; NumericQ[result]], True, TimeConstraint -> timeLimit, TestID -> "quiet-computation-succeeds@@Tests/FindRootOptim/fastRootOptions.wlt:1110,1-1118,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f2, {1., 2.}, Jacobian -> df2]; NumericQ[result] && Abs[result^2 - 4] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "root-at-boundary@@Tests/FindRootOptim/fastRootOptions.wlt:1160,1-1168,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, {1.4, 1., 2.}, Jacobian -> df1]; NumericQ[result] && Abs[result^2 - 2] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "1D-full-spec-with-jacobian@@Tests/FindRootOptim/fastRootOptions.wlt:1210,1-1218,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, {1.4, 1., 2.}]; NumericQ[result] && Abs[result^2 - 2] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "1D-full-spec-no-jacobian@@Tests/FindRootOptim/fastRootOptions.wlt:1260,1-1268,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, {Automatic, 1., 2.}, Jacobian -> df1]; NumericQ[result] && Abs[result^2 - 2] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "1D-automatic-x0@@Tests/FindRootOptim/fastRootOptions.wlt:1310,1-1318,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, 1.4, Jacobian -> df1]; NumericQ[result] && Abs[result^2 - 2] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "1D-scalar-x0-with-jacobian@@Tests/FindRootOptim/fastRootOptions.wlt:1360,1-1368,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, 1.4]; NumericQ[result] && Abs[result^2 - 2] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "1D-scalar-x0-no-jacobian@@Tests/FindRootOptim/fastRootOptions.wlt:1410,1-1418,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[fND2, {{1.2, 1.2}}, Jacobian -> dfND2]; VectorQ[result, NumericQ] && Max[Abs[fND2[result]]] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "nD-nested-x0-with-jacobian@@Tests/FindRootOptim/fastRootOptions.wlt:1460,1-1468,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[fND2, {{1.2, 1.2}}]; VectorQ[result, NumericQ] && Max[Abs[fND2[result]]] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "nD-nested-x0-no-jacobian@@Tests/FindRootOptim/fastRootOptions.wlt:1510,1-1518,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[fND2, {{1.5, 1.5}}, Jacobian -> dfND2]; VectorQ[result, NumericQ] && Max[Abs[result - {expectedND2, expectedND2}]] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "nD-nested-x0-correct-root@@Tests/FindRootOptim/fastRootOptions.wlt:1560,1-1568,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[fND2, {{0.5, 2.}, {0.5, 2.}}, Jacobian -> dfND2]; VectorQ[result, NumericQ] && Max[Abs[fND2[result]]] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "nD-bounds-new-format@@Tests/FindRootOptim/fastRootOptions.wlt:1610,1-1618,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[fND2, {{1.2, 0.5, 2.}, {1.2, 0.5, 2.}}, Jacobian -> dfND2]; VectorQ[result, NumericQ] && Max[Abs[fND2[result]]] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "nD-full-spec-new-format@@Tests/FindRootOptim/fastRootOptions.wlt:1660,1-1668,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[f1, {1.2, 1.2}, Jacobian -> df1]; result === $Failed], True, {FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot::badbounds}, TimeConstraint -> timeLimit, TestID -> "disambiguation-flat-is-1D-bounds@@Tests/FindRootOptim/fastRootOptions.wlt:1710,1-1720,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[fND3, {{0.9, 0.9, 0.9}}, Jacobian -> dfND3]; VectorQ[result, NumericQ] && Length[result] == 3 && Max[Abs[fND3[result]]] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "nD-3D-nested-x0@@Tests/FindRootOptim/fastRootOptions.wlt:1762,1-1770,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[fND2, {{1.2, 1.2}}, Jacobian -> dfND2, "Return" -> "Rule"]; MatchQ[result, {(_ -> _?NumericQ)..}] && Length[result] == 2], True, TimeConstraint -> timeLimit, TestID -> "nD-nested-x0-return-rule@@Tests/FindRootOptim/fastRootOptions.wlt:1812,1-1820,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result}, result = fastRoot[fND2, {{1.2, 1.2}}, Jacobian -> dfND2, Method -> "Secant"]; VectorQ[result, NumericQ] && Max[Abs[fND2[result]]] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "nD-nested-x0-method-secant@@Tests/FindRootOptim/fastRootOptions.wlt:1862,1-1870,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result, badDfND}, badDfND[z_] := {{0., 0.}, {0., 0.}}; result = fastRoot[fND2, {{1.2, 1.2}}, Jacobian -> badDfND]; VectorQ[result, NumericQ] && Max[Abs[fND2[result]]] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "nD-newton-fails-fallback@@Tests/FindRootOptim/fastRootOptions.wlt:1912,1-1921,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result, badDfND}, badDfND[z_] := {{0., 0.}, {0., 0.}}; result = fastRoot[fND2, {{0.5, 2.}, {0.5, 2.}}, Jacobian -> badDfND]; VectorQ[result, NumericQ] && Max[Abs[fND2[result]]] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "nD-bounds-newton-fails-fallback@@Tests/FindRootOptim/fastRootOptions.wlt:1963,1-1972,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result, badDF}, badDF[z_] := 0.; result = fastRoot[f1, {1., 2.}, Jacobian -> badDF]; NumericQ[result] && Abs[result^2 - 2] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "1D-bracketed-newton-fails-brent-fallback@@Tests/FindRootOptim/fastRootOptions.wlt:2014,1-2023,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result, badDF}, badDF[z_] := 0.; result = fastRoot[f2, {2.5, 3.}, Jacobian -> badDF]; NumericQ[result] && Abs[result^2 - 4] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "1D-nonbracketed-newton-fails-secant-fallback@@Tests/FindRootOptim/fastRootOptions.wlt:2065,1-2074,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[Module[{result, badDfND3}, badDfND3[z_] := {{0., 0., 0.}, {0., 0., 0.}, {0., 0., 0.}}; result = fastRoot[fND3, {{0.9, 0.9, 0.9}}, Jacobian -> badDfND3]; VectorQ[result, NumericQ] && Length[result] == 3 && Max[Abs[fND3[result]]] < 10^(-6)], True, TimeConstraint -> timeLimit, TestID -> "3D-newton-fails-fallback@@Tests/FindRootOptim/fastRootOptions.wlt:2116,1-2125,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[fastRoot[f1, Automatic] === $Failed, True, {FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot::noautox0}, TimeConstraint -> timeLimit, TestID -> "error-noautox0-scalar@@Tests/FindRootOptim/fastRootOptions.wlt:2167,1-2173,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[fastRoot[f1, "invalid"] === $Failed, True, {FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot::badspec}, TimeConstraint -> timeLimit, TestID -> "error-badspec-string@@Tests/FindRootOptim/fastRootOptions.wlt:2215,1-2221,4"]],
    HoldComplete[Needs["FernandoDuarte`LongRunRisk`Tools`FindRootOptim`"]; ],
    HoldComplete[fastRoot = FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot; ],
    HoldComplete[timeLimit = 5; ],
    HoldComplete[tolSameTest = Function[{actual, expected}, Module[{a, e}, a = actual /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; e = expected /. {(_ -> (v_)?NumericQ) :> v, {_ -> (v_)?NumericQ} :> v}; Max[Abs[Flatten[{a}] - Flatten[{e}]]] < 10^(-6)]]; ],
    HoldComplete[f1[z_] := z[[1]]^2 - 2; ],
    HoldComplete[df1[z_] := 2*z[[1]]; ],
    HoldComplete[f2[z_] := z[[1]]^2 - 4; ],
    HoldComplete[df2[z_] := 2*z[[1]]; ],
    HoldComplete[fcos[z_] := Cos[z[[1]]]; ],
    HoldComplete[dfcos[z_] := -Sin[z[[1]]]; ],
    HoldComplete[fsin[z_] := Sin[z[[1]]] - 0.5; ],
    HoldComplete[fexp[z_] := Exp[z[[1]]] - 3; ],
    HoldComplete[fcubic[z_] := z[[1]]^3 - 8; ],
    HoldComplete[fND2[z_] := {z[[1]]^2 + z[[2]] - 3, z[[1]] + z[[2]]^2 - 3}; ],
    HoldComplete[dfND2[z_] := {{2*z[[1]], 1}, {1, 2*z[[2]]}}; ],
    HoldComplete[expectedND2 = N[(-1 + Sqrt[13])/2]; ],
    HoldComplete[fND3[z_] := {z[[1]] + z[[2]] + z[[3]] - 3, z[[1]]*z[[2]] - 1, z[[2]]*z[[3]] - 1}; ],
    HoldComplete[dfND3[z_] := {{1, 1, 1}, {z[[2]], z[[1]], 0}, {0, z[[3]], z[[2]]}}; ],
    HoldComplete[VerificationTest[fastRoot[fND2, {{2., 1.}, {0.5, 2.}}, Jacobian -> dfND2] === $Failed, True, {FernandoDuarte`LongRunRisk`Tools`FindRootOptim`fastRoot::badbounds}, TimeConstraint -> timeLimit, TestID -> "error-badbounds-nD@@Tests/FindRootOptim/fastRootOptions.wlt:2263,1-2269,4"]],
    HoldComplete[End[]],
    HoldComplete[EndTestSection[]]
};

(* --- options --- *)
Options[GenerateWLT] = {
    "OutputTestHead" -> TestCreate,
    "DefaultTimeConstraint" -> 30,
    "PreserveExistingTestIDs" -> False,
    "PreserveExistingTimeConstraints" -> True,
    "TestIDPrefix" -> "fastRootOptions",
    "HashLength" -> 8,
    "TargetRelativeWLTPath" -> "../../FindRootOptim/fastRootOptions.wlt"
};

(* --- internal helpers --- *)
testExprQ[HoldComplete[VerificationTest[___]]] := True;
testExprQ[HoldComplete[TestCreate[___]]] := True;
testExprQ[HoldComplete[IntermediateTest[___]]] := True;
testExprQ[_] := False;

hasOptionQ[hc_HoldComplete, sym_Symbol] := !FreeQ[hc, HoldPattern[(sym -> _) | (sym :> _)]];

removeOption[hc_HoldComplete, sym_Symbol] :=
    FixedPoint[
        ReplaceAll[
            #,
            HoldComplete[head_[pre___, (sym -> _) | (sym :> _), post___]] :> HoldComplete[head[pre, post]]
        ] &,
        hc
    ];

appendOption[hc_HoldComplete, rule_] := hc /. HoldComplete[head_[args___]] :> HoldComplete[head[args, rule]];

convertTestHead[hc_HoldComplete, Automatic] := hc;
convertTestHead[hc_HoldComplete, newHead_Symbol] :=
    hc /. HoldComplete[(VerificationTest | TestCreate | IntermediateTest)[args___]] :> HoldComplete[newHead[args]];

stripForHash[hc_HoldComplete] := removeOption[removeOption[hc, TestID], TimeConstraint];

shortHash[hc_HoldComplete, n_Integer?Positive] :=
    Module[{h = IntegerString[Hash[stripForHash[hc], "SHA256"], 36]}, StringTake[h, UpTo[n]]];

makeTestID[prefix_String, key_String, occ_Integer] :=
    If[occ <= 1, StringJoin[prefix, "-", key], StringJoin[prefix, "-", key, "-", IntegerString[occ]]];

ensureTestID[hc_HoldComplete, id_, preserveQ_] :=
    Module[{out = hc},
        If[preserveQ && hasOptionQ[out, TestID], Return[out]];
        out = removeOption[out, TestID];
        appendOption[out, TestID -> id]
    ];

ensureTimeConstraint[hc_HoldComplete, tc_, preserveQ_] :=
    Module[{out = hc},
        If[preserveQ && hasOptionQ[out, TimeConstraint], Return[out]];
        out = removeOption[out, TimeConstraint];
        appendOption[out, TimeConstraint -> tc]
    ];

transformTest[hc_HoldComplete, id_, opts:OptionsPattern[GenerateWLT]] :=
    Module[{out = hc, head, tc, keepID, keepTC},
        head  = OptionValue["OutputTestHead"];
        tc    = OptionValue["DefaultTimeConstraint"];
        keepID = TrueQ @ OptionValue["PreserveExistingTestIDs"];
        keepTC = TrueQ @ OptionValue["PreserveExistingTimeConstraints"];
        out = convertTestHead[out, head];
        out = ensureTestID[out, id, keepID];
        out = ensureTimeConstraint[out, tc, keepTC];
        out
    ];

stripHold[HoldComplete[e_]] :=
    Module[{s = ToString[HoldForm[e], InputForm, PageWidth -> Infinity]},
        If[StringStartsQ[s, "HoldForm["] && StringEndsQ[s, "]"], StringTake[s, {10, -2}], s]
    ];

writeHeldExpressions[file_String, exprs_List] :=
    Module[{res},
        res = Quiet@Check[Export[file, exprs, "HeldExpressions"], $Failed];
        If[res === $Failed,
            Export[file, StringRiffle[stripHold /@ exprs, "\n\n"], "Text"];
        ];
        file
    ];

defaultTarget[opts:OptionsPattern[GenerateWLT]] :=
    Module[{rel = OptionValue["TargetRelativeWLTPath"], here},
        here = If[StringQ[$InputFileName] && $InputFileName =!= "", DirectoryName[$InputFileName], Directory[]];
        ExpandFileName @ FileNameJoin[{here, rel}]
    ];

GenerateWLT[target_: Automatic, opts:OptionsPattern[]] :=
    Module[{outFile, outExprs, seen = <||>, prefix, n, key, occ, id},
        outFile = Replace[target, Automatic :> defaultTarget[opts]];
        CreateDirectory[DirectoryName[outFile], CreateIntermediateDirectories -> True];
        prefix = OptionValue["TestIDPrefix"];
        prefix = If[StringQ[prefix], prefix, ToString[prefix, InputForm]];
        n = OptionValue["HashLength"];
        n = If[IntegerQ[n] && n > 0, n, 8];
        outExprs = Map[
            Function[hc,
                If[testExprQ[hc],
                    key = shortHash[hc, n];
                    occ = Lookup[seen, key, 0] + 1;
                    seen[key] = occ;
                    id = makeTestID[prefix, key, occ];
                    transformTest[hc, id, opts],
                    hc
                ]
            ],
            $sourceExpressions
        ];
        writeHeldExpressions[outFile, outExprs];
        outFile
    ];

End[];
EndPackage[];
