name: Check
on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]
concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true
env:
  RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
  WOLFRAMINIT: -pwfile !cloudlm.wolfram.com -entitlement ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
  WLPR_PACLET_SITE: https://resources.wolframcloud.com/PacletRepository/pacletsite
  PACLET_CICD_VERSION: 0.36.2
jobs:
  Check:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:14.3.0
      options: --user root --privileged --init
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Check
        id: check-paclet
        uses: WolframResearch/check-paclet@v1.11.0
        with:
          debug: "true"
          target: Check
          paclet_cicd_version: ${{ env.PACLET_CICD_VERSION }}
        env:
          WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
          RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}

      - name: Upload workflow values
        if: always() && env.PACLET_WORKFLOW_VALUES
        uses: actions/upload-artifact@v5
        with:
          name: check-workflow-values
          path: ${{ env.PACLET_WORKFLOW_VALUES }}
          if-no-files-found: ignore
